languageCode = "zh-cn"
languageName = "简体中文"
weight = 4
title = "Euphia"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/blowfish_logo_transparent.png"
  description = ""

[params.author]
  name = "Euphia"
  image = "img/blowfish_logo.png"
  headline = ""
  bio = ""
  links = [
    { x-twitter = "https://twitter.com/iseuphia" },
    { github = "https://github.com/euphia" },
  ]