languageCode = "ja"
languageName = "日本語"
weight = 3
title = "Euphia"

[params]
  displayName = "日本語"
  isoCode = "ja"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/blowfish_logo_transparent.png"
  description = ""

[params.author]
  name = "Euphia"
  image = "img/blowfish_logo.png"
  headline = ""
  bio = ""
  links = [
    { x-twitter = "https://twitter.com/iseuphia" },
    { github = "https://github.com/euphia" },
  ]
