languageCode = "en"
languageName = "English"
weight = 1
title = "Euphia"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "Euphia's blog."

[params.author]
  name = "Euphia"
  email = ""
  image = "img/blowfish_logo.png"
  headline = ""
  bio = ""
  links = [
    { x-twitter = "https://twitter.com/iseuphia" },
    { github = "https://github.com/euphia" },
  ]